### ISSUE TITLE
Application must be closed manually before update

### ISSUE THREAD

**Issue by laurinkeithdavis** [sippi90/chocolateyautomaticpackages#1]
https://social.technet.microsoft.com/Forums/windows/en-US/4c8fad53-d7ad-4e9a-9569-454d9c793bd3/powershell-to-close-a-running-program-gracefully-without-uses-interact?forum=w7itprogeneral

Maybe something like this would work:

https://social.technet.microsoft.com/Forums/windows/en-US/4c8fad53-d7ad-4e9a-9569-454d9c793bd3/powershell-to-close-a-running-program-gracefully-without-uses-interact?forum=w7itprogeneral

**Get-Process Myprogram |   Foreach-Object { $_.CloseMainWindow() | Out-Null } | stop-process –force**

**Comment by SebastianK90** [comment]
https://groups.google.com/d/msg/chocolatey/MlTq-fJfld8/ZCJbxQ9_AAAJ I will provide chocolateyBeforeModify.ps1
