### ISSUE TITLE
reshack.portable fails to install because it has the SHA256 code of the old version 5.1.8

### ISSUE THREAD

**Issue by jpluimers** [sippi90/chocolateyautomaticpackages#16]
Log:

``` text
C:\bin\bin>choco upgrade --yes reshack.portable
Chocolatey v0.11.3
Upgrading the following packages:
reshack.portable
By upgrading, you accept licenses for the packages.
reshack.portable is not installed. Installing...
Progress: Downloading reshack.portable 5.1.8... 100%
Progress: Downloading reshack.portable 5.1.8... 100%

reshack.portable v5.1.8 [Approved]
reshack.portable package files upgrade completed. Performing other installation steps.
Downloading reshack.portable
  from 'http://www.angusj.com/resourcehacker/resource_hacker.zip'
Progress: 100% - Completed download of C:\Users\jeroenp\AppData\Local\Temp\chocolatey\reshack.portable\5.1.8\resource_hacker.zip (3.02 MB).
Download of resource_hacker.zip (3.02 MB) completed.
Error - hashes do not match. Actual value was 'D158BEBC2993CF6BEBF2C23A93572A68544C2BA5AE056538F70A58075C9392D6'.
ERROR: Checksum for 'C:\Users\jeroenp\AppData\Local\Temp\chocolatey\reshack.portable\5.1.8\resource_hacker.zip' did not meet 'c5a0e7f4b8f1089418520562c13d45f8e6fcfff65537830fb166f218b095708c' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
The upgrade of reshack.portable was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\reshack.portable\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey upgraded 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - reshack.portable (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\reshack.portable\tools\chocolateyInstall.ps1'.
 See log for details.
``` 

Related https://github.com/AngusJohnson/Image32/issues/14

The reason is that he current http://www.angusj.com/resourcehacker/resource_hacker.zip with `ResourceHacker.exe` version 5.1.8.360 has SHA256 `D158BEBC2993CF6BEBF2C23A93572A68544C2BA5AE056538F70A58075C9392D6` 

https://github.com/SebastianK90/chocolateyautomaticpackages/blob/master/reshack.portable/tools/chocolateyInstall.ps1 does the SHA256 value check and needs updating.

Note: I'm not sure what https://github.com/SebastianK90/chocolateyautomaticpackages/blob/master/reshack.portable/update.ps1 is for. Shouldn't it be deleted?

**Comment by SebastianK90** [comment]
changed update.ps1 to double check the fileversion.
new version is also pushed.
closed.

**Comment by jpluimers** [comment]
Thanks a lot!

And thanks for showing me how https://github.com/SebastianK90/chocolateyautomaticpackages/blob/master/reshack.portable/update.ps1 is part of the auto-update mechanism. Splendid!

- Fix of the auto-update script: https://github.com/SebastianK90/chocolateyautomaticpackages/commit/73ede3db5e5125477b884dd5ad0e1444927f3023
- Auto-update applied: https://github.com/SebastianK90/chocolateyautomaticpackages/commit/c6ea3137f80607b469ac74b7ae3b38c4aed24da2
