### ISSUE TITLE
Closing paint.net is delayed by 10 seconds

### ISSUE THREAD

**Issue by jmeile** [sippi90/chocolateyautomaticpackages#17]
Hi

I installed paint.net.portable in two different computers and in both of them, whenever you close paint.net, it will take 10 seconds. If I install this two portable versions, the issue won't happen there:
https://github.com/paintdotnet/release/releases/download/v5.0.2/paint.net.5.0.2.portable.x64.zip
https://portableapps.com/apps/graphics_pictures/paintdotnet-portable

Here more info about my installation:

**Chocolatey Version**
1.3.1

**Chocolatey License**
None

**Package Version**
5.0.2

**Current Behaviour**
Closing the application last 10 seconds. The non-portable version closes immediately.

**Expected Behaviour**
Application closing without delay

**Steps To Reproduce**

1. Open Paint.net
2. Close Paint.net and wait 10 seconds
3. Paint.net will be closed

**Environment**
- Operating System: Microsoft Windows NT 10.0.19045.0 or also known as: Windows 10, version 22H2, OS build: 19045.2486
- PowerShell Version: 5.1.19041.2673
- Installed packages:
   - Chocolatey 1.3.1
   - chocolatey-compatibility.extension 1.0.0
   - chocolatey-core.extension 1.4.0
   - paint.net.portable 5.0.2

Best regards
Josef

**Comment by SebastianK90** [comment]
fixed in https://github.com/SebastianK90/chocolateyautomaticpackages/commit/85357bb96060ed4d1eef1fa7a83fdcef899c8227

**Comment by jmeile** [comment]
Hi Sebastian

Is this fixed implemented in the current version from the Chocolatey repository? If yes, then it is still being delayed.

Since the last version, which you uploaded yesterday: march 30th, isn't approved yet, I forced the installation like this:
`choco install paint.net.portable --version=5.0.3`

But as I said, the delay is still there.

**Comment by SebastianK90** [comment]
Mhh,I,'ve tested positive yesterday. I'll have another look and reopen the issue. Thanks for reporting! Am 31.03.2023 12:52 schrieb Josef Meile ***@***.***>:
Hi Sebastian
Is this fixed implemented in the current version from the Chocolatey repository? If yes, then it is still being delayed.
Since the last version, which you uploaded yesterday: march 30th, isn't approved yet, I forced the installation like this:
choco install paint.net.portable --version=5.0.3
But as I said, the delay is still there.

**Comment by SebastianK90** [comment]
Seems not fixed

**Comment by jmeile** [comment]
I just tried the version that you uploaded today and it is closing without a delay :-)

Thanks
