### ISSUE TITLE
Error during telegram.install installing

### ISSUE THREAD

**Issue by SiriosDev** [sippi90/chocolateyautomaticpackages#18]
`ERROR: Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String.
The install of telegram.install was NOT successful.`

**Comment by SebastianK90** [comment]
I've updated the package. Once it's gone through moderation, could you please see if it's fixed for you now?
Thank you very much!

**Comment by SiriosDev** [comment]
I will, but how will I know that moderation has posted the new one?

**Comment by SebastianK90** [comment]
It has the timestamp 230802 in the version.Am 02.08.2023 14:33 schrieb Sirios_Dev ***@***.***>:
I will, but how will I know that moderation has posted the new one?

**Comment by SiriosDev** [comment]
works👍
