### ISSUE TITLE
cemu: 1.13.2 download is corrupt; upgrade to 1.13.2d

### ISSUE THREAD

**Issue by Zenexer** [sippi90/chocolateyautomaticpackages#3]
cemu appears to have updated their release without changing the version number or URL.

* Current hash: `9002ebebf8cfed4c2d1eeec345c37967982b1927b2a31e6a206968473d96c03e`
* Current version: 1.13.2
* Relevant choco package commit: https://github.com/sippi90/chocolateyautomaticpackages/commit/037915ef79b912a2b9271d61cc5fae285ed3ea41
* Commit date: 2018-10-03T18:12:16Z
* Last-Modified header sent by cemu.info: Fri, 05 Oct 2018 15:36:57 GMT

Looks like it was modified almost two days after the choco package update.

Edit: Take a look at [cemu's changelog](http://cemu.info/changelog/cemu_1_13_2.txt).  They have letter suffixes (1.13.2, 1.13.2b, 1.13.2c, 1.13.2d).  They're currently on d.  Unfortunately, the URL doesn't seem to include these suffixes.

Edit 2: The URL for 1.13.2d is actually different: http://cemu.info/releases/cemu_1.13.2d.zip  And it has a different hash: `8e9737575c319d40756fbce05b7ebb82f4a5fc3968e49b432a73bb07769fc86f`  I'm not going to bother trying to figure out exactly what happened with 1.13.2; I'll just submit a PR for 1.13.2d.

Edit 3: Actually, I figured it out: the 1.13.2.zip download is corrupt.  It's about 3/5 the size that it should be, and 7-zip can't open it.

**Comment by SebastianK90** [comment]
thx, New version is pushed!

**Comment by Zenexer** [comment]
@sippi90  Did you fix the script?  If not, I'll make a PR for that.

**Comment by Zenexer** [comment]
That PR will take a letter suffix (or multiple letters), turn it into a numeric revision, and multiply by 100, per the recommendation [here](https://github.com/chocolatey/choco/wiki/CreatePackages#versioning-recommendations).

Examples:

* 1.13.2 -> 1.13.2.0
* 1.13.2a -> 1.13.2.100
* 1.13.2ab -> 1.13.2.2700

It multiplies by 100 in case you ever need to make changes to the package between cemu releases.  Without that, you wouldn't be able to update the package without colliding with a potential cemu version, since you can only have a maximum of four components to the version number.
