### ISSUE TITLE
Cemu improper install location

### ISSUE THREAD

**Issue by AeliusSaionji** [sippi90/chocolateyautomaticpackages#5]
You have cemu installing to the chocolatey toolsdir which should not contain user data and is read-only in certain configurations. It would be more appropriate to install to the folder formerly know by "binroot" https://chocolatey.org/docs/helpers-get-tools-location

**Comment by AeliusSaionji** [comment]
![image](https://user-images.githubusercontent.com/4342746/66543988-e2dc5d80-eb04-11e9-9a0c-c7ecb20d0c9e.png)

this is intersecting with chocolatey bug/undesirable design in a way that is creating problems for me as a maintainer now. Please fix this. Also, I am aware a cemu setup guide says to run Cemu as admin, but please don't. When you install it to C:\tools\cemu, it will not be required and I expect to not run things as admin when they do not need to be run as admin.

**Comment by SebastianK90** [comment]
Sorry, I am very busy at the moment. Could you please create a PR.

**Comment by AeliusSaionji** [comment]
Ok, I am working on this and I have some questions about your script.
This line here:
~`$latest = (Get-ChildItem $toolsPath -Recurse -ErrorAction SilentlyContinue | Where-Object {$_.Name -like '*cemu*'} | sort {$_.CreationTime} | select -First 1).FullName`
Only matches cemu.exe. Why not move cemu.exe directly? Why is there all of this directory searching and filtering? If the binary is know to change, why `'*cemu*'` rather than `'*cemu*.exe'`? Or, `'*.exe'`?~

~But is this even necessary? According to the wiki, 
http://wiki.cemu.info/wiki/Serfrosts_Cemu_Setup_Guide~
![image](https://user-images.githubusercontent.com/4342746/67663836-bca82180-f93c-11e9-9805-8051b9cb001a.png)

Edit, I see now, nevermind.

**Comment by AeliusSaionji** [comment]
Ah, another reason we should not have the cemu data in chocolatey dirs: I just ran into chocolatey trying to move the cemu dir from lib to lib-bkp, which is a lot of files and again I ran into permission issues even as elevated admin, and otherwise this adds several minutes onto the package update time during which chocolatey appears to be frozen.

**Comment by AeliusSaionji** [comment]
I'm having trouble with this. Unfortunately chocolatey is moving the existing cemu to lib-bkp and then deleting it. I'll have to sleep on this, but let me know if you have ideas for how to migrate the existing install to the new location.

**Comment by SebastianK90** [comment]
Thats why I determine the latest cemu.exe via creationtime. Once I'm back from vacation I will look into this, if I can find some spare time.

**Comment by sippi90** [comment]
Removed necessity of admin rights and changed install-path to binroot\cemu

**Comment by AeliusSaionji** [comment]
Thanks for working on this. If there's no better way than just backing up lib-bkp, then it just occurred to me that you can set up a condition `if cemu.exe exists in lib-bkp, move to $(Get-ToolsLocation)\cemu{date}`

**Comment by AeliusSaionji** [comment]
thanks!
